In [2]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

In [3]:
subreddit_name = "Nietzsche"

df_subreddit = pd.read_csv(f"{subreddit_name}/{subreddit_name}_mentalhealth_common_author_posts_processed.csv")
df_subreddit['isodate'] = pd.to_datetime(df_subreddit["isodate"])
df_subreddit.drop(['index'], axis = 1, inplace = True)
df_subreddit.head()

,isodate,subreddit,author,body,source,processed,Polarity,Subjectivity,emp_help,emp_office,...,nrc_anger,nrc_anticip,nrc_trust,nrc_surprise,nrc_positive,nrc_negative,nrc_sadness,nrc_disgust,nrc_joy,nrc_anticipation
0,2022-10-06 21:54:18,Nietzsche,slavetothegiven,yeh tried all the usual. but i thought it was ...,Nietzsche,"['yeh', 'try', 'usual', 'think', 'kaufmann', '...",-0.250000,0.250000,0.0,0.0,...,0.0,0.0,0.50,0.0,0.50,0.00,0.0,0.0,0.0,0.0
1,2022-09-02 20:27:23,realhousewives,slavetothegiven,what why on earth is dorit returning and erica...,Nietzsche,"['earth', 'dorit', 'return', 'erica', 'demote'...",0.000000,0.750000,0.0,0.0,...,0.0,0.0,0.00,0.0,0.00,0.50,0.5,0.0,0.0,0.0
2,2022-08-20 15:14:40,realhousewives,slavetothegiven,wait what did teddi say?,Nietzsche,"['wait', 'teddi', 'say']",0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.00,0.0,0.00,0.50,0.0,0.0,0.0,0.5
3,2022-08-20 15:10:18,realhousewives,slavetothegiven,wait when did Sutton mock her nationality?,Nietzsche,"['wait', 'sutton', 'mock', 'nationality']",0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.00,0.0,0.00,0.50,0.0,0.0,0.0,0.5
4,2022-08-18 16:15:58,realhousewives,slavetothegiven,reality tv is all about getting clearly person...,Nietzsche,"['reality', 'tv', 'get', 'clearly', 'personali...",-0.033333,0.594444,0.0,0.0,...,0.0,0.0,0.25,0.0,0.25,0.25,0.0,0.0,0.0,0.0

In [11]:
df_subreddit.groupby(by=['subreddit']).size().sort_values(ascending= False).head(20)

subreddit
Nietzsche              1149
AskReddit               394
Jung                    302
aspergers               237
askphilosophy           228
ADHD                    154
JordanPeterson          147
depression              147
NoFap                   138
autism                  120
BPD                     114
schizophrenia           114
unpopularopinion        113
SuicideWatch            106
nihilism                106
relationship_advice     105
redscarepod             100
conspiracy               96
Stoicism                 95
socialskills             90
dtype: int64

In [7]:
type(df_subreddit['isodate'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [13]:
def get_aggregated_df(agg_cols):
    groupby_str = f"df_subreddit.groupby(by =[pd.Grouper(key='isodate', axis=0, freq='D')] ).agg("
    for col in agg_cols:
        col_string = f"{col}=('{col}', np.sum),"
        groupby_str += col_string
    
    groupby_str = groupby_str[:-1]
    groupby_str += ").reset_index()"
    return eval(groupby_str)

aggregated_df = get_aggregated_df(df_subreddit.columns[-11:])
aggregated_df.head(40)

,isodate,nrc_fear,nrc_anger,nrc_anticip,nrc_trust,nrc_surprise,nrc_positive,nrc_negative,nrc_sadness,nrc_disgust,nrc_joy,nrc_anticipation
0,2011-12-22,0.059509,0.022472,0.0,0.372867,0.167291,0.611527,0.171244,0.059509,0.074698,0.178527,0.282355
1,2011-12-23,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2011-12-24,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2011-12-25,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2011-12-26,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,2011-12-27,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,2011-12-28,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,2011-12-29,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,2011-12-30,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,2011-12-31,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,2012-01-01,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,2012-01-02,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,2012-01-03,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,2012-01-04,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,2012-01-05,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,2012-01-06,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,2012-01-07,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,2012-01-08,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,2012-01-09,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,2012-01-10,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,2012-01-11,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,2012-01-12,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,2012-01-13,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,2012-01-14,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,2012-01-15,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,2012-01-16,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,2012-01-17,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,2012-01-18,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,2012-01-19,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,2012-01-20,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,2012-01-21,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,2012-01-22,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,2012-01-23,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,2012-01-24,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,2012-01-25,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,2012-01-26,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,2012-01-27,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,2012-01-28,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,2012-01-29,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,2012-01-30,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [15]:
aggregated_df["nrc_positive"].plot()
plt.show()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.